site_name: Webscraping mit Puppeteer
site_url: https://swi-hdm.github.io/webscraping-intro/

# Theme Configuration
theme:
  name: material
  logo: assets/images/omm-logo_orange.png
  language: de  # Sets UI (Search, navigation) to German
  palette:
    primary: blue
  features:
    - content.code.copy    # Copy button
    - content.code.select  # Select all button (optional but nice)

# Markdown Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # OPTIONAL: Highlights inline code like `print()`
  - pymdownx.superfences  # CRITICAL: Allows arbitrary nesting of code blocks

# Navigation
nav:
  - Home: index.md
